### PR TITLE
Add Git Diff Margin to the community extensions list

### PR DESCRIPTION
**Pull request by laurentkempe**

### CODE REVIEW

**Comment by ExtendVS** [comment]
Hi there, I have a lot of merge conflicts. Would you mind merging yours for me? Thanks!

**Comment by laurentkempe** [comment]
Hi, how do you want me to do that I don't have access to your repo!

**Comment by davemckeown** [comment]
@laurentkempe you need to pull the latest changes to your fork, fix the conflict and then push the changes back to update your PR

git fetch Microsoft
git checkout Microsoft/gh-pages
(fix conflict and push changes)

**Comment by laurentkempe** [comment]
Damn I guess I was really tired! Thanks @davemckeown

**Comment by laurentkempe** [comment]
@ExtendVS Done!

**Comment by laurentkempe** [comment]
:+1:

**Pull request merged**
